% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={🌬️🗳 Assignment 2: Wind Turbines, Matching, and Difference-in-Differences},
  pdfauthor={EDS 241 / ESM 244 (DUE: 2/4/26)},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{🌬️🗳 Assignment 2: Wind Turbines, Matching, and
Difference-in-Differences}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Replicate causal inference identification strategies in Stokes
(2015)}
\author{EDS 241 / ESM 244 (DUE: 2/4/26)}
\date{1/26/26}

\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[frame hidden, borderline west={3pt}{0pt}{shadecolor}, sharp corners, interior hidden, enhanced, boxrule=0pt, breakable]}{\end{tcolorbox}}\fi

\hypertarget{assignment-instructions}{%
\subsubsection{Assignment instructions}\label{assignment-instructions}}

Working with classmates to troubleshoot code and concepts is encouraged.
If you collaborate, list collaborators at the top of your submission.

All written responses must be written independently (in your own words).

Keep your work readable: Use clear headings and label plot elements
thoughtfully.

Assignment submission (YOUR NAME): Melannie Moreno Rolón

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{introduction}{%
\subsubsection{Introduction}\label{introduction}}

In this assignment you will be doing political weather forecasting
except the ``storms'' we care about are electoral swings that might
follow local wind turbine development.

In Stokes (2015), the idea is that a policy with diffuse benefits
(cleaner electricity) can create concentrated local costs (turbines
nearby), and those local opponents may ``send a signal'' at the ballot
box (i.e., NIMBYISM). Your job is to use two statistical tools:

\begin{itemize}
\tightlist
\item
  Matching: Can we create a more apples-to-apples comparison between
  precincts that did vs.~did not end up near turbine proposals?
\item
  Fixed effects + Difference-in-Differences: Can we use repeated
  elections to estimate how within-precinct changes in turbine exposure
  relate to changes in incumbent vote share?
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{learning-goal-replicate-the-matching-and-fixed-effects-analyses-from-study}{%
\subsubsection{Learning goal: Replicate the matching and fixed effects
analyses from
study:}\label{learning-goal-replicate-the-matching-and-fixed-effects-analyses-from-study}}

\begin{quote}
Stokes (2015): \emph{``Electoral Backlash against Climate Policy: A
Natural Experiment on Retrospective Voting and Local Resistance to
Public Policy}.
\end{quote}

\begin{itemize}
\tightlist
\item
  \textbf{Study:}
  \href{https://drive.google.com/file/d/1y2Okzjq2EA43AW5JzCvFS8ecLpeP6NKh/view?usp=sharing}{Stokes
  (2015) - Article}
\item
  \textbf{Data source:}
  \href{https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SDUGCC}{Dataverse-Stokes2015}
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, toprule=.15mm, leftrule=.75mm, opacityback=0, colframe=quarto-callout-color-frame, left=2mm, breakable, bottomrule=.15mm, arc=.35mm, colback=white, rightrule=.15mm]

\texttt{NOTE:} Replication of study estimates will be approximate. An
alternative matching procedure and fixed effects estimation package are
utilized in this assignment for illustration purposes.

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{setup-load-libraries}{%
\subsubsection{Setup: Load libraries}\label{setup-load-libraries}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{-1}
\tightlist
\item
  Load libraries (+ install if needed)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(here)}
\FunctionTok{library}\NormalTok{(janitor)}
\FunctionTok{library}\NormalTok{(jtools)}

\FunctionTok{library}\NormalTok{(gtsummary)}
\FunctionTok{library}\NormalTok{(gt)}

\FunctionTok{library}\NormalTok{(MatchIt) }\CommentTok{\# matching}
\FunctionTok{library}\NormalTok{(cobalt)  }\CommentTok{\# balance + love plots}

\FunctionTok{library}\NormalTok{(fixest) }\CommentTok{\# fast fixed effects}
\FunctionTok{library}\NormalTok{(scales) }\CommentTok{\# plotting}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-1-study-background}{%
\subsubsection{Part 1: Study Background}\label{part-1-study-background}}

\hypertarget{a.-dive-into-the-details-of-the-study-design-and-evaluation-plan}{%
\paragraph{\texorpdfstring{\textbf{1A.} Dive into the details of the
study design and evaluation
plan}{1A. Dive into the details of the study design and evaluation plan}}\label{a.-dive-into-the-details-of-the-study-design-and-evaluation-plan}}

\begin{quote}
Goal: Get familiar with the study setting, environmental issue, and
policy under evaluation.
\end{quote}

\begin{tcolorbox}[enhanced jigsaw, toprule=.15mm, leftrule=.75mm, opacityback=0, colframe=quarto-callout-color-frame, left=2mm, breakable, bottomrule=.15mm, arc=.35mm, colback=white, rightrule=.15mm]

\texttt{NOTE:} Read over study to inform your response to the assignment
questions. For this assignment we will skip-over sections that describe
the \emph{Instrumental Variables} identification strategy. We will cover
instrumental variable designs weeks 6-7.

\end{tcolorbox}

\textbf{1A.Q1} Summarize the environmental policy issue, the outcome of
interest, and the intervention being evaluated. Be sure to include a
brief description of each of the following key elements of the study:
unit of analysis, outcome, treatment, comparison group):

\emph{Response:} This paper examines electoral backlash against climate
policy by studying local resistance to wind energy projects in Ontario,
Canada. The study uses a natural experiment created by the Green Energy
Act to evaluate whether proximity to proposed or operational wind
turbines led to electoral punishment of the incumbent provincial Liberal
Party. The outcome of interest is incumbent vote share and voter turnout
and was measured at the provincial electoral precinct level. The
treatment is defined as precinct-level exposure to wind turbines, while
the comparison group consists of similar precincts in wind-feasible
districts without turbine exposure.

\textbf{1A.Q2} Why might turbine proposals be correlated with baseline
political preferences or rural areas? Provide 2 plausible mechanisms,
and explain why that creates confounding.

\hypertarget{response-according-to-the-study-turbine-proposals-may-be-correlated-with-baseline-political-preferences-or-rural-areas-for-two-reasons.-first-wind-turbines-were-more-likely-to-be-sited-in-rural-areas-due-to-land-availability-and-low-population-density-and-rural-precincts-tend-to-have-different-political-preferences-and-lower-baseline-support-for-the-incumbent-liberal-party.-second-developers-may-have-anticipated-less-resistance-in-communities-with-lower-political-influence-or-mobilization-capacity-leading-turbines-to-be-placed-in-areas-already-predisposed-to-oppose-the-government.-both-mechanisms-create-confounding-because-the-observed-electoral-backlash-could-reflect-pre-existing-political-preferences-rather-than-a-direct-causal-effect-of-turbine-exposure.}{%
\subsection{\texorpdfstring{\emph{Response:} According to the study,
turbine proposals may be correlated with baseline political preferences
or rural areas for two reasons. First, wind turbines were more likely to
be sited in rural areas due to land availability and low population
density, and rural precincts tend to have different political
preferences and lower baseline support for the incumbent Liberal Party.
Second, developers may have anticipated less resistance in communities
with lower political influence or mobilization capacity, leading
turbines to be placed in areas already predisposed to oppose the
government. Both mechanisms create confounding because the observed
electoral backlash could reflect pre-existing political preferences
rather than a direct causal effect of turbine
exposure.}{Response: According to the study, turbine proposals may be correlated with baseline political preferences or rural areas for two reasons. First, wind turbines were more likely to be sited in rural areas due to land availability and low population density, and rural precincts tend to have different political preferences and lower baseline support for the incumbent Liberal Party. Second, developers may have anticipated less resistance in communities with lower political influence or mobilization capacity, leading turbines to be placed in areas already predisposed to oppose the government. Both mechanisms create confounding because the observed electoral backlash could reflect pre-existing political preferences rather than a direct causal effect of turbine exposure.}}\label{response-according-to-the-study-turbine-proposals-may-be-correlated-with-baseline-political-preferences-or-rural-areas-for-two-reasons.-first-wind-turbines-were-more-likely-to-be-sited-in-rural-areas-due-to-land-availability-and-low-population-density-and-rural-precincts-tend-to-have-different-political-preferences-and-lower-baseline-support-for-the-incumbent-liberal-party.-second-developers-may-have-anticipated-less-resistance-in-communities-with-lower-political-influence-or-mobilization-capacity-leading-turbines-to-be-placed-in-areas-already-predisposed-to-oppose-the-government.-both-mechanisms-create-confounding-because-the-observed-electoral-backlash-could-reflect-pre-existing-political-preferences-rather-than-a-direct-causal-effect-of-turbine-exposure.}}

\hypertarget{b.-break-down-the-causal-inference-strategy-and-identify-threats-to-identification}{%
\paragraph{\texorpdfstring{\textbf{1B.} Break down the causal inference
strategy and identify threats to
identification:}{1B. Break down the causal inference strategy and identify threats to identification:}}\label{b.-break-down-the-causal-inference-strategy-and-identify-threats-to-identification}}

\textbf{1B.Q1} What is the key identifying assumption for a fixed
effects / Difference-in-Difference design? Explain how this assumption
when satisfied provides evidence of causal effect:

\emph{Response:} The key identifying assumption of a fixed effects /
difference-in-differences design is the parallel trends assumption. This
assumption states that, in the absence of treatment, treated and control
precincts would have followed the same trend in electoral outcomes over
time. When this assumption is satisfied, any divergence in outcomes
after treatment can be attributed to the treatment itself rather than to
pre-existing differences between groups, and thus, provide evidence of a
causal effect.

\textbf{1B.Q2} What is the reason for using a fixed effects approach
from a causal inference perspective? Summarize within the context of
study (in your own words).

\emph{Response:} From a causal inference perspective, the fixed effects
approach is used to control for time-invariant characteristics of
precincts that could confound the relationship between wind turbines and
voting behavior. Examples of these characteristics are political
preferences, the rural setting, or socioeconomic differences.

\textbf{1B.Q3} What part of the SUTVA assumption is most likely violated
in the context of this study design (and why)?

\emph{Response:} The assumption of SUTVA most likely to be violated is
the no-interference assumption. The no-interference assumption states
that the treatment status of one unit does not affect the outcomes of
other units. In this study, voters in precincts without turbines may
still be affected by nearby turbines through visual exposure, noise, or
local political mobilization. Therefore, outcomes in control precincts
could be influenced by the treatment in neighboring precincts.

\textbf{1B.Q4} Why does spillover matter when estimating an unbiased
treatment effect?

\emph{Response:} Spillover matters because if control units are
indirectly affected by treatment, the estimated difference between
treated and control groups will be biased toward zero. This makes the
treatment effect appear smaller than it actually is, and the control
group is no longer a valid counterfactual for what would have happened
in the absence of treatment.

\textbf{1B.Q5} How do the authors assess the risk of spillovers, and
what analytic choice do they make to attempt to mitigate the risk that
spillover biases the causal estimate?

\emph{Response:} The authors assessed the risk of spillover by
estimating treatment effects at increasing distance bands from wind
turbines up to 5 km, and showing that vote share declines persist up to
about 3 km. To mitigate the risk that spillover biases the causal
estimate, the researchers excluded precincts within 6 km of turbines
from the control group when estimating distance-related effects.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-2-matching}{%
\subsubsection{Part 2: Matching}\label{part-2-matching}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

We will start by evaluating the 2007 survey (cross-sectional) data.
Treatment is defined by whether a precinct is near a turbine proposal
(within 3 km).

\begin{quote}
Goal: Match precincts using pre-treatment covariates and then estimate
the effect of proposed wind turbines on incumbent vote share.
\end{quote}

\hypertarget{a.-load-data-for-matching}{%
\paragraph{\texorpdfstring{\textbf{2A.} Load data for
matching}{2A. Load data for matching}}\label{a.-load-data-for-matching}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Read in data file \texttt{stokes15\_survey2007.csv}
\item
  Code \texttt{precinct\_id} and \texttt{district\_id} as factors
\item
  Take a look at the data
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Read in data file and code \textasciigrave{}precinct\_id\textasciigrave{} and \textasciigrave{}district\_id\textasciigrave{} as factors}
\NormalTok{match\_data }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"stokes15\_survey2007.csv"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{precinct\_id =} \FunctionTok{factor}\NormalTok{(precinct\_id),}
           \AttributeTok{district\_id =} \FunctionTok{factor}\NormalTok{(district\_id))}

\CommentTok{\# Take a look at the data}
\FunctionTok{glimpse}\NormalTok{(match\_data)    }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 5,973
Columns: 16
$ precinct_id          <fct> 10.001.10.1., 10.002.10.1., 10.003.10.2., 10.004.~
$ district_id          <fct> 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1~
$ change_liberal       <dbl> 0.08456503, 0.13210655, 0.18208628, 0.15422953, 0~
$ proposed_turbine_3km <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0~
$ log_wind_power       <dbl> 6.645013, 6.295443, 6.310994, 6.654216, 6.104257,~
$ log_home_val_07      <dbl> 12.27993, 12.28202, 12.28125, 12.26825, 12.37316,~
$ p_uni_degree         <dbl> 0.19225123, 0.22043792, 0.22079883, 0.12727273, 0~
$ log_median_inc       <dbl> 10.286860, 10.309722, 10.309530, 10.147100, 10.28~
$ log_pop_denc         <dbl> -1.79255050, -3.49902997, -0.31878753, -0.4490713~
$ mindistlake          <dbl> 0.0000000, 1.3834536, 2.6037725, 0.0000000, 0.953~
$ mindistlake_sq       <dbl> 0.00000000, 1.91394392, 6.77963136, 0.00000000, 0~
$ longitude            <dbl> -81.67554, -81.64687, -81.47904, -81.69842, -81.3~
$ long_sq              <dbl> 6670.894, 6666.211, 6638.833, 6674.633, 6616.192,~
$ latitude             <dbl> 45.30674, 45.25790, 45.22889, 45.20118, 45.17166,~
$ lat_sq               <dbl> 2052.701, 2048.277, 2045.653, 2043.146, 2040.479,~
$ long_lat             <dbl> -3700.453, -3695.166, -3685.207, -3692.865, -3674~
\end{verbatim}

\textbf{2A.Q1} Intuition check: \textbf{Why match?} Explain rationale
for using this method.

\emph{Response:} Matching is used here to make sure that treated and
control precincts are comparable on observed pre-treatment
characteristics that could influence voting behavior. Since we will be
balancing these covariates, matching will reduce confounding and make
differences in incumbent vote share more plausibly attributable to
proximity to turbine proposals rather than other underlying differences
between precincts.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{b.-check-imbalance-before-matching}{%
\paragraph{\texorpdfstring{\textbf{2B.} Check imbalance (before
matching)}{2B. Check imbalance (before matching)}}\label{b.-check-imbalance-before-matching}}

\begin{itemize}
\tightlist
\item
  Create a covariate \emph{balance table} comparing treated and control
  precincts
\item
  Treatment indicator: \texttt{proposed\_turbine\_3km}
\item
  Include pre-treatment covariates: \texttt{log\_home\_val\_07},
  \texttt{p\_uni\_degree}, \texttt{log\_median\_inc},
  \texttt{log\_pop\_denc}
\item
  Use the \texttt{tbl\_summary()} function from the
  \texttt{\{gtsummary\}} package.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Covariate balance table}
\NormalTok{match\_data }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{select}\NormalTok{(}
\NormalTok{        proposed\_turbine\_3km, log\_home\_val\_07, p\_uni\_degree, log\_median\_inc,}
\NormalTok{        log\_pop\_denc}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{tbl\_summary}\NormalTok{(}
        \AttributeTok{by =}\NormalTok{ proposed\_turbine\_3km,}
        \AttributeTok{statistic =} \FunctionTok{list}\NormalTok{(}
            \FunctionTok{all\_continuous}\NormalTok{() }\SpecialCharTok{\textasciitilde{}} \StringTok{"\{mean\} (\{sd\})"}\NormalTok{,}
            \FunctionTok{all\_categorical}\NormalTok{() }\SpecialCharTok{\textasciitilde{}} \StringTok{"\{n\} (\{p\}\%)"}
\NormalTok{        )}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{modify\_header}\NormalTok{(label }\SpecialCharTok{\textasciitilde{}} \StringTok{"**Covariate**"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{modify\_spanning\_header}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"stat\_1"}\NormalTok{, }\StringTok{"stat\_2"}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"**Group**"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcc}
\toprule
 & \multicolumn{2}{c}{{\textbf{Group}}} \\ 
\cmidrule(lr){2-3}
\textbf{Covariate} & \textbf{0}  N = 5,619\textsuperscript{\textit{1}} & \textbf{1}  N = 354\textsuperscript{\textit{1}} \\ 
\midrule\addlinespace[2.5pt]
log\_home\_val\_07 & 12.26 (0.37) & 12.29 (0.29) \\ 
p\_uni\_degree & 0.17 (0.12) & 0.13 (0.09) \\ 
log\_median\_inc & 10.32 (0.22) & 10.31 (0.19) \\ 
log\_pop\_denc & 5.12 (2.40) & 3.54 (1.78) \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textsuperscript{\textit{1}}Mean (SD)\\
\end{minipage}
\end{table}

\textbf{2B.Q1} Summarize the table output: Which covariates look
balanced/imbalanced?

\emph{Response:} \texttt{log\_pop\_denc} and \texttt{p\_uni\_degree}
appear more imbalanced across treated and control precincts, while
\texttt{log\_home\_val\_07} and \texttt{log\_median\_inc} appear to be
more balanced.

\textbf{2B.Q2} Describe in your own words why these covariates might be
expected to confound the treatment estimate:

\emph{Response (2-4 sentences):} These covariates may confound the
treatment estimate because they are related to turbine siting and voting
behavior. Differences in population density, education, income, and home
values reflect underlying socioeconomic and political characteristics
that could influence incumbent vote share independent of turbine
exposure.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{2B.Q3} Intuition check: What type of data do you need to conduct
a matching analysis?

\emph{Response:} Conducting a matching analysis requires cross-sectional
or pre-treatment data which includes a treatment indicator,
pre-treatment covariates, and an outcome variable.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{conduct-matching-estimation-using-the-matchit-package}{%
\subsubsection{\texorpdfstring{Conduct matching estimation using the
\{\texttt{MatchIt}\}
package:}{Conduct matching estimation using the \{MatchIt\} package:}}\label{conduct-matching-estimation-using-the-matchit-package}}

📜 \href{https://kosukeimai.github.io/MatchIt/}{Documentation - MatchIt}

Learning goals:

\begin{itemize}
\tightlist
\item
  Approximate the Mahalanobis matching method used in Stokes (2015)
\item
  Implement another common matching approach called
  \texttt{propensity\ score\ matching}
\end{itemize}

\begin{tcolorbox}[enhanced jigsaw, toprule=.15mm, leftrule=.75mm, opacityback=0, colframe=quarto-callout-color-frame, left=2mm, breakable, bottomrule=.15mm, arc=.35mm, colback=white, rightrule=.15mm]

\texttt{NOTE}: In the replication code associated with Stokes (2015) the
\{\texttt{AER}\} package is used for Mahalanobis matching. In this
assignment we use the \{\texttt{MatchIt}\} package. The results are
comparable but will not be exactly the same.

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{c.-mahalanobis-nearest-neighbor-matching}{%
\subsubsection{2C. Mahalanobis nearest-neighbor
matching}\label{c.-mahalanobis-nearest-neighbor-matching}}

\begin{itemize}
\tightlist
\item
  Conduct Mahalanobis matching\\
\item
  Use nearest-neighbor match without replacement using Mahalanobis
  distance
\item
  Use 1-to-1 matching (match one control unit to each treatment unit)
\item
  Extract the matched data using \texttt{match.data()}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2412026}\NormalTok{)}

\NormalTok{match\_model }\OtherTok{\textless{}{-}} \FunctionTok{matchit}\NormalTok{(}
    \AttributeTok{formula =}\NormalTok{ proposed\_turbine\_3km  }\SpecialCharTok{\textasciitilde{}}\NormalTok{  log\_home\_val\_07 }\SpecialCharTok{+}\NormalTok{ p\_uni\_degree }\SpecialCharTok{+}\NormalTok{ log\_median\_inc }\SpecialCharTok{+} 
\NormalTok{         log\_pop\_denc,}
  \AttributeTok{data =}\NormalTok{ match\_data, }
  \AttributeTok{method =} \StringTok{"nearest"}\NormalTok{,       }\CommentTok{\# Nearest neighbor matching}
  \AttributeTok{distance =} \StringTok{"mahalanobis"}\NormalTok{, }\CommentTok{\# Mahalanobis distance}
  \AttributeTok{ratio =} \DecValTok{1}\NormalTok{,                }\CommentTok{\# Match one control unit to one treatment unit (1:1 matching)}
  \AttributeTok{replace =} \ConstantTok{FALSE}           \CommentTok{\# Control observations are not replaced}
\NormalTok{)}

\CommentTok{\# Extract matched data}
\NormalTok{matched\_data }\OtherTok{\textless{}{-}} \FunctionTok{match.data}\NormalTok{(match\_model)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(match\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
matchit(formula = proposed_turbine_3km ~ log_home_val_07 + p_uni_degree + 
    log_median_inc + log_pop_denc, data = match_data, method = "nearest", 
    distance = "mahalanobis", replace = FALSE, ratio = 1)

Summary of Balance for All Data:
                Means Treated Means Control Std. Mean Diff. Var. Ratio
log_home_val_07       12.2948       12.2620          0.1138     0.5941
p_uni_degree           0.1257        0.1688         -0.5032     0.4916
log_median_inc        10.3096       10.3219         -0.0636     0.7581
log_pop_denc           3.5398        5.1192         -0.8897     0.5474
                eCDF Mean eCDF Max
log_home_val_07    0.0382   0.0881
p_uni_degree       0.1032   0.1769
log_median_inc     0.0355   0.0750
log_pop_denc       0.2099   0.3713

Summary of Balance for Matched Data:
                Means Treated Means Control Std. Mean Diff. Var. Ratio
log_home_val_07       12.2948       12.2975         -0.0093     1.0063
p_uni_degree           0.1257        0.1262         -0.0060     1.0485
log_median_inc        10.3096       10.3096          0.0002     1.0403
log_pop_denc           3.5398        3.5982         -0.0329     0.9784
                eCDF Mean eCDF Max Std. Pair Dist.
log_home_val_07    0.0075   0.0282          0.1334
p_uni_degree       0.0088   0.0367          0.1642
log_median_inc     0.0073   0.0395          0.1225
log_pop_denc       0.0109   0.0508          0.1485

Sample Sizes:
          Control Treated
All          5619     354
Matched       354     354
Unmatched    5265       0
Discarded       0       0
\end{verbatim}

\textbf{2C.Q1} Using the \texttt{summary()} output: Which covariate had
the largest and smallest \texttt{Std.\ Mean\ Diff.} before matching.
Next, compare largest/smallest \texttt{Std.\ Mean\ Diff.} after
matching.

\emph{Response:} \texttt{log\_pop\_denc} had the largest
\texttt{Std.\ Mean\ Diff.} before matching, while
\texttt{log\_median\_inc} had the smallest. After matching,
\texttt{log\_pop\_denc} still had the largest \texttt{Std.\ Mean\ Diff}
and \texttt{log\_median\_inc} had the smallest.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{d.-create-a-love-plot-using-love.plot}{%
\paragraph{\texorpdfstring{2D. Create a ``love plot'' using
\texttt{love.plot()}
❤️}{2D. Create a ``love plot'' using love.plot() ❤️}}\label{d.-create-a-love-plot-using-love.plot}}

📜 \href{https://ngreifer.github.io/cobalt/}{Documentation - cobalt}

\begin{itemize}
\tightlist
\item
  Plot mean differences for data before \& after matching across all
  pre-treatment covariates
\item
  This is an effective way to evaluate how effective matching was at
  achieving balance.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{itemize}
\tightlist
\item
  Make a love plot of standardized mean differences (SMDs) before vs
  after matching.
\item
  Include a threshold line at 0.1.
\item
  In love plot display \texttt{mean.diffs}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{new\_names }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
    \AttributeTok{old =} \FunctionTok{c}\NormalTok{(}\StringTok{"log\_home\_val\_07"}\NormalTok{, }\StringTok{"p\_uni\_degree"}\NormalTok{, }\StringTok{"log\_median\_inc"}\NormalTok{, }\StringTok{"log\_pop\_denc"}\NormalTok{),}
    \AttributeTok{new =} \FunctionTok{c}\NormalTok{(}\StringTok{"Home Value (log)"}\NormalTok{, }\StringTok{"Percent University Degree"}\NormalTok{,}
            \StringTok{"Median Income (log)"}\NormalTok{, }\StringTok{"Population Density (log)"}\NormalTok{))}

\CommentTok{\# Love plot}
\FunctionTok{love.plot}\NormalTok{(match\_model, }
          \AttributeTok{stats =} \StringTok{"mean.diffs"}\NormalTok{,}
          \AttributeTok{thresholds =} \FunctionTok{c}\NormalTok{(}\AttributeTok{m =} \FloatTok{0.1}\NormalTok{),}
          \AttributeTok{var.names =}\NormalTok{ new\_names)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{HW2_START_files/figure-pdf/unnamed-chunk-6-1.pdf}

}

\end{figure}

\textbf{2D.Q1} Interpret the love plot in your own words:

\emph{Response:} The love plot shows a significant imbalance in
population density and educational attainment before matching, where the
standardized mean differences are well above the 0.1 threshold. After
matching, all covariates are well balanced and fall within the
threshold, therefore, the matching procedure successfully reduced
observable differences between treated and control precincts.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{propensity-score-matching}{%
\subsubsection{Propensity score
matching}\label{propensity-score-matching}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{e.-propensity-score-matching-psm}{%
\paragraph{2E. Propensity Score Matching
(PSM)}\label{e.-propensity-score-matching-psm}}

\begin{itemize}
\tightlist
\item
  Estimate 1:1 nearest-neighbor Propensity Score Matching
\item
  Same code as above except change \texttt{distance\ =\ "logit"}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2412026}\NormalTok{)}

\NormalTok{propensity\_scores }\OtherTok{\textless{}{-}} \FunctionTok{matchit}\NormalTok{(}
    \AttributeTok{formula =}\NormalTok{ proposed\_turbine\_3km  }\SpecialCharTok{\textasciitilde{}}\NormalTok{  log\_home\_val\_07 }\SpecialCharTok{+}\NormalTok{ p\_uni\_degree }\SpecialCharTok{+}\NormalTok{ log\_median\_inc }\SpecialCharTok{+} 
\NormalTok{         log\_pop\_denc,}
  \AttributeTok{data =}\NormalTok{ match\_data, }
  \AttributeTok{method =} \StringTok{"nearest"}\NormalTok{,       }\CommentTok{\# Nearest neighbor matching}
  \AttributeTok{distance =} \StringTok{"logit"}\NormalTok{,       }\CommentTok{\# logit distance}
  \AttributeTok{ratio =} \DecValTok{1}\NormalTok{,                }\CommentTok{\# Match one control unit to one treatment unit (1:1 matching)}
  \AttributeTok{replace =} \ConstantTok{FALSE}           \CommentTok{\# Control observations are not replaced}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{create-table-displaying-covariate-balance-using-cobaltbal.tab}{%
\paragraph{\texorpdfstring{Create table displaying covariate balance
using
\texttt{cobalt::bal.tab()}}{Create table displaying covariate balance using cobalt::bal.tab()}}\label{create-table-displaying-covariate-balance-using-cobaltbal.tab}}

📜 \href{https://ngreifer.github.io/cobalt/}{Documentation - cobalt}

Use \texttt{bal.tab()} to report balance before and after matching.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bal.tab}\NormalTok{(propensity\_scores, }
        \AttributeTok{var.names =}\NormalTok{ new\_names) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Balance Measures
                    Type Diff.Adj
distance        Distance   0.0001
log_home_val_07  Contin.   0.0205
p_uni_degree     Contin.   0.0457
log_median_inc   Contin.  -0.0042
log_pop_denc     Contin.  -0.0365

Sample sizes
          Control Treated
All          5619     354
Matched       354     354
Unmatched    5265       0
\end{verbatim}

\textbf{2E.Q1} Compare Mahalanobis vs propensity score matching. Which
method did a better job at achieving balance?

\emph{Response:} Propensity score matching achieved a slightly better
balance, since the adjusted standardized mean differences are
consistently very small across all covariates and had a slightly tighter
balance than Mahalanobis matching.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{f.-estimate-an-effect-in-the-matched-sample}{%
\paragraph{2F. Estimate an effect in the matched
sample}\label{f.-estimate-an-effect-in-the-matched-sample}}

Using the matched data (Mahalanobis method), estimate the effect of
treatment on the change in incumbent vote share
(\texttt{change\_liberal}).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg\_match }\OtherTok{\textless{}{-}}  \FunctionTok{lm}\NormalTok{(}
\NormalTok{  change\_liberal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ proposed\_turbine\_3km,}
  \AttributeTok{data =}\NormalTok{ matched\_data,}
  \AttributeTok{weights =}\NormalTok{ matched\_data}\SpecialCharTok{$}\NormalTok{weights)}

\FunctionTok{summ}\NormalTok{(reg\_match, }\AttributeTok{model.fit =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{708}\\
Dependent variable & change\_liberal\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{OLS linear regression}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & t val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{-0.07} & \cellcolor{gray!10}{0.01} & \cellcolor{gray!10}{-10.96} & \cellcolor{gray!10}{0.00}\\
proposed\_turbine\_3km & -0.06 & 0.01 & -7.25 & 0.00\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: OLS
\end{tablenotes}
\end{threeparttable}
\end{table}

\textbf{2F.Q1} Have you identified a causal estimate using this
approach: Why or why not?

\emph{Response:} This approach identified a causal estimate that depends
on satisfying the matching assumptions. The analysis reduces confounding
from observed pre-treatment covariates by matching treated and control
precincts, and under the assumption that there are no unobserved
confounders, the estimated effect is −0.06. This would be the causal
effect of proximity to a turbine proposal on incumbent vote share.

\textbf{2F.Q2} When using a matching method, what is the main threat to
causal identification?

\emph{Response:} The main threat to causal identification when using the
matching method is the possibility of having an unobserved confounding.
If there are factors left unmeasured that could affect turbine siting
and voting behavior, the treatment estimate may be biased.

\textbf{2F.Q3} Describe why the treatment estimate represents the
\texttt{Average\ Treatment\ for\ the\ Treated\ (ATT)} and explain why
this is the case relative to estimation of the
\texttt{Average\ Treatment\ Effect\ (ATE)}.

\emph{Response:} The treatment estimate represents the Average Treatment
Effect on the Treated (ATT) because the matching procedure pairs each
treated precinct with similar control precincts and then estimates the
effect for those treated units. The control units are also selected to
resemble the treated group, where the estimate reflects the effect of
treatment on precincts that actually experienced turbine exposure.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-3-panel-data-fixed-effects-and-difference-in-difference}{%
\subsubsection{Part 3: Panel Data, Fixed Effects, and
Difference-in-Difference}\label{part-3-panel-data-fixed-effects-and-difference-in-difference}}

\textbf{Data source:}
\href{https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SDUGCC}{Dataverse-Stokes2015}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{a-read-in-the-panel-data-code-variables-precinct_id-and-year-as-factors}{%
\paragraph{\texorpdfstring{\textbf{3A:} Read in the panel data + code
variables \texttt{precinct\_id} and \texttt{year} as
factors}{3A: Read in the panel data + code variables precinct\_id and year as factors}}\label{a-read-in-the-panel-data-code-variables-precinct_id-and-year-as-factors}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{panel\_data }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"Stokes15\_panel\_data.csv"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{precinct\_id =} \FunctionTok{factor}\NormalTok{(precinct\_id),}
           \AttributeTok{year =} \FunctionTok{factor}\NormalTok{(year))}

\FunctionTok{glimpse}\NormalTok{(panel\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 18,558
Columns: 14
$ precinct_id         <fct> 10.001.10.1., 10.001.10.1., 10.001.10.1., 10.002.1~
$ year                <fct> 2003, 2007, 2011, 2003, 2007, 2011, 2003, 2007, 20~
$ perc_lib            <dbl> 0.4341600, 0.2162162, 0.3007812, 0.4341600, 0.1686~
$ proposed_turbine    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
$ operational_turbine <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
$ log_pop             <dbl> 5.8077175, 3.9076310, 3.8643798, 5.1978116, 2.1535~
$ log_pop_denc        <dbl> -1.4725813, -1.2777149, -1.7925505, -2.0824872, 0.~
$ log_median_inc      <dbl> 9.955869, 9.754840, 10.286860, 9.956546, 9.699630,~
$ log_home_val        <dbl> 11.81378, 12.27993, 12.79206, 11.86941, 12.28202, ~
$ avg_home_val        <dbl> 135100.7, 215330.9, 359353.6, 142830.1, 215781.7, ~
$ unemploy_rate       <dbl> 5.258431, 11.205697, 12.797498, 5.858203, 14.30746~
$ p_uni_degree        <dbl> 0.25098436, 0.19586050, 0.19225123, 0.26564499, 0.~
$ p_immigrant         <dbl> 0.15281480, 0.11723295, 0.12858559, 0.16840506, 0.~
$ p_housing_own       <dbl> 0.6654168, 0.9334555, 0.9410068, 0.6665852, 0.9176~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# HINT: Try running \textasciigrave{}tabyl(panel\_data$year)\textasciigrave{}. Review article to make sense of the row numbers (n).}
\FunctionTok{tabyl}\NormalTok{(panel\_data}\SpecialCharTok{$}\NormalTok{year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 panel_data$year    n   percent
            2003 6186 0.3333333
            2007 6186 0.3333333
            2011 6186 0.3333333
\end{verbatim}

\textbf{3A.Q1:} Why are there 18,558 rows in \texttt{panel\_data}?

\emph{Response:} The dataset is structured in long format. Each precinct
appears once for each election year. There are 6,186 precincts observed
in three election years (2003, 2007, and 2011), therefore, the dataset
contains 18,558 rows in total.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How many years are included in the panel?}
\FunctionTok{n\_distinct}\NormalTok{(panel\_data}\SpecialCharTok{$}\NormalTok{year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
    \CommentTok{\# There are 3 years included in the panel (2003, 2007, 2011).}

\CommentTok{\# How many precincts are there?}
\FunctionTok{n\_distinct}\NormalTok{(panel\_data}\SpecialCharTok{$}\NormalTok{precinct\_id)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 6186
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
    \CommentTok{\# There are 6,186 total precincts.}
\end{Highlighting}
\end{Shaded}

\textbf{3A.Q2:} How many unique precincts are \emph{ever treated} (i.e.,
\texttt{proposed} \& \texttt{operational})?

\emph{Response:} There are 184 unique precincts that are \emph{ever
treated}. Of these, 52 precincts eventually have an operational turbine.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{panel\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(precinct\_id) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{ever\_proposed    =} \FunctionTok{any}\NormalTok{(proposed\_turbine }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{ever\_operational =} \FunctionTok{any}\NormalTok{(operational\_turbine }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n\_ever\_proposed    =} \FunctionTok{sum}\NormalTok{(ever\_proposed),}
    \AttributeTok{n\_ever\_operational =} \FunctionTok{sum}\NormalTok{(ever\_operational))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 1 x 2
  n_ever_proposed n_ever_operational
            <int>              <int>
1             184                 52
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{b.-plot-and-evaluate-parallel-trends-replicate-figure.2-stokes-2015}{%
\paragraph{\texorpdfstring{\textbf{3B.} Plot and evaluate parallel
trends: Replicate \texttt{Figure.2} (Stokes,
2015)}{3B. Plot and evaluate parallel trends: Replicate Figure.2 (Stokes, 2015)}}\label{b.-plot-and-evaluate-parallel-trends-replicate-figure.2-stokes-2015}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Create indicators for whether each precinct is ever treated by 2011
  (\texttt{treat\_p}, \texttt{treat\_o}; separate indicator for
  proposals and operational turbines).
\item
  Plot mean incumbent vote share by year for treated vs control
  precincts (with 95\% CIs).
\item
  Facet by turbine type (proposed \& operational)
\end{enumerate}

Step 1: Prepare data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{trends\_data }\OtherTok{\textless{}{-}}\NormalTok{ panel\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(precinct\_id) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{treat\_p =} \FunctionTok{as.integer}\NormalTok{(}\FunctionTok{any}\NormalTok{(proposed\_turbine }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),  }\CommentTok{\# ever proposed (in any year)}
    \AttributeTok{treat\_o =} \FunctionTok{as.integer}\NormalTok{(}\FunctionTok{any}\NormalTok{(operational\_turbine }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# ever operational (in any year)}
  \FunctionTok{ungroup}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pivot\_longer}\NormalTok{(}\FunctionTok{c}\NormalTok{(treat\_p, treat\_o),}
               \AttributeTok{names\_to =} \StringTok{"turbine\_type"}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{"treat"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}
      \AttributeTok{turbine\_type =} \FunctionTok{factor}\NormalTok{(turbine\_type,}
                            \AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"treat\_p"}\NormalTok{, }\StringTok{"treat\_o"}\NormalTok{),}
                            \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Proposed turbines"}\NormalTok{, }\StringTok{"Operational turbines"}\NormalTok{)),  }
    \AttributeTok{status =} \FunctionTok{if\_else}\NormalTok{(treat }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\StringTok{"Treated"}\NormalTok{, }\StringTok{"Control"}\NormalTok{),}
    \AttributeTok{year   =} \FunctionTok{factor}\NormalTok{(year))}
\end{Highlighting}
\end{Shaded}

Step 2: Create trends plot

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pd }\OtherTok{\textless{}{-}} \FunctionTok{position\_dodge}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.15}\NormalTok{)}

\NormalTok{trends\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(turbine\_type, status, year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(perc\_lib, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{n    =} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(perc\_lib)),}
    \AttributeTok{se   =} \FunctionTok{sd}\NormalTok{(perc\_lib, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n), }
    \AttributeTok{ci   =} \FunctionTok{qt}\NormalTok{(.}\DecValTok{975}\NormalTok{, }\AttributeTok{df =} \FunctionTok{pmax}\NormalTok{(n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)) }\SpecialCharTok{*}\NormalTok{ se,}
    \AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(year, mean, }\AttributeTok{color =}\NormalTok{ status, }\AttributeTok{group =}\NormalTok{ status)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{position =}\NormalTok{ pd, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{position =}\NormalTok{ pd, }\AttributeTok{size =} \FloatTok{2.6}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_errorbar}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{ymin =}\NormalTok{ mean }\SpecialCharTok{{-}}\NormalTok{ ci, }\AttributeTok{ymax =}\NormalTok{ mean }\SpecialCharTok{+}\NormalTok{ ci),}
    \AttributeTok{position =}\NormalTok{ pd, }\AttributeTok{width =}\NormalTok{ .}\DecValTok{12}\NormalTok{, }\AttributeTok{linewidth =}\NormalTok{ .}\DecValTok{7}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ turbine\_type, }\AttributeTok{nrow =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\AttributeTok{Control =} \StringTok{"\#0072B2"}\NormalTok{, }\AttributeTok{Treated =} \StringTok{"\#B22222"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{percent\_format}\NormalTok{(}\AttributeTok{accuracy =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{coord\_cartesian}\NormalTok{(}\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(.}\DecValTok{20}\NormalTok{, .}\DecValTok{57}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Figure 2. Trends in the Governing Party’s Vote Share"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Election Year"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Liberal Party Vote Share"}\NormalTok{,}
    \AttributeTok{color =} \ConstantTok{NULL}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{14}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{panel.grid.minor =} \FunctionTok{element\_blank}\NormalTok{(),}
    \AttributeTok{legend.position =} \StringTok{"bottom"}\NormalTok{,}
    \AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}[H]

{\centering \includegraphics{HW2_START_files/figure-pdf/unnamed-chunk-14-1.pdf}

}

\end{figure}

\textbf{3B.Q1:} Write a short paragraph assessing the parallel trends
assumption for each outcome.

\emph{Response (4-6 sentences):} I assessed the parallel trends
assumption by comparing trends in Liberal vote share for treated and
control precincts prior to treatment in the plot. In the proposed
turbines panel, the treated and control precincts follow similar trends
between 2003 and 2007. This trend suggests that the parallel trends
assumption is plausible for this outcome. In the operational turbines
panel, the treated precincts start with higher Liberal vote share in
2003, but the decline from 2003 to 2007 is broadly similar in direction
to that of control precincts. Although their levels differ, the
pre-treatment trends do not show clear divergence prior to 2007.
Overall, the figure provides visual support for the parallel trends
assumption, but the evidence is stronger for proposed turbines than for
operational turbines.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{estimating-fixed-effects-models-did-for-proposals}{%
\subsubsection{Estimating Fixed Effects Models (DiD) for
proposals}\label{estimating-fixed-effects-models-did-for-proposals}}

\[
\text{Y}_{it}
=  \alpha_0 +
\beta \cdot (\text{proposed_turbine}_{it})
+ \gamma_i
+ \delta_t
+ \varepsilon_{it}
\]

\begin{itemize}
\tightlist
\item
  \(Y_{it}\) is the vote share for the Liberal Party in precinct
  \emph{i} in time \emph{t}
\item
  \(\beta\) is the treatment effect of a turbine being proposed within a
  precinct
\item
  \(\gamma_i\) is the precinct fixed effect
\item
  \(\delta_t\) is the year fixed effect
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{example-1-randomly-sample-40-precincts}{%
\subsubsection{Example 1: Randomly sample 40
precincts}\label{example-1-randomly-sample-40-precincts}}

\begin{itemize}
\tightlist
\item
  To illustrate the ``dummy variable method'' of estimating fixed
  effects using the the general \texttt{lm()} function we are going to
  randomly sample 40 precincts (20 ``treated'' precincts with proposed
  turbines).
\item
  If we attempted to use this approach with the full sample estimating
  all 6185 (n-1) precinct-level coefficients is impractical (it would
  take a long time).
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{40002026}\NormalTok{)}

\NormalTok{precinct\_frame }\OtherTok{\textless{}{-}}\NormalTok{ panel\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(precinct\_id) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{proposed\_turbine\_any =} \FunctionTok{as.integer}\NormalTok{(}\FunctionTok{any}\NormalTok{(proposed\_turbine }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{ids\_40 }\OtherTok{\textless{}{-}}\NormalTok{ precinct\_frame }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(proposed\_turbine\_any) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =} \DecValTok{20}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ungroup}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(precinct\_id)}

\NormalTok{sample\_40\_precincts }\OtherTok{\textless{}{-}}\NormalTok{ panel\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{semi\_join}\NormalTok{(ids\_40, }\AttributeTok{by =} \StringTok{"precinct\_id"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{c-estimate-a-fixed-effects-model-using-lm-with-fixed-effects-added-for-precinct-and-year-using-the-sample-of-40-precincts-just-created.}{%
\paragraph{\texorpdfstring{\textbf{3C:} Estimate a fixed effects model
using \texttt{lm()} with fixed effects added for \texttt{precinct} and
\texttt{year} using the sample of 40 precincts just
created.}{3C: Estimate a fixed effects model using lm() with fixed effects added for precinct and year using the sample of 40 precincts just created.}}\label{c-estimate-a-fixed-effects-model-using-lm-with-fixed-effects-added-for-precinct-and-year-using-the-sample-of-40-precincts-just-created.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1\_ff }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(perc\_lib }\SpecialCharTok{\textasciitilde{}}\NormalTok{ proposed\_turbine }\SpecialCharTok{+}\NormalTok{ precinct\_id }\SpecialCharTok{+}\NormalTok{ year,}
                \AttributeTok{data =}\NormalTok{ sample\_40\_precincts)}

\FunctionTok{summ}\NormalTok{(model1\_ff, }\AttributeTok{model.fit =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{120}\\
Dependent variable & perc\_lib\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{OLS linear regression}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & t val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{0.275} & \cellcolor{gray!10}{0.050} & \cellcolor{gray!10}{5.460} & \cellcolor{gray!10}{0.000}\\
proposed\_turbine & -0.057 & 0.031 & -1.858 & 0.067\\
\cellcolor{gray!10}{precinct\_id10.115s.10.84.} & \cellcolor{gray!10}{0.166} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{2.402} & \cellcolor{gray!10}{0.019}\\
precinct\_id105.038.105.45. & 0.053 & 0.069 & 0.765 & 0.447\\
\cellcolor{gray!10}{precinct\_id14.149.14.79.} & \cellcolor{gray!10}{0.208} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{2.976} & \cellcolor{gray!10}{0.004}\\
\addlinespace
precinct\_id14.168.14.82. & 0.192 & 0.070 & 2.749 & 0.007\\
\cellcolor{gray!10}{precinct\_id18.003.18.1.} & \cellcolor{gray!10}{0.121} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{1.738} & \cellcolor{gray!10}{0.086}\\
precinct\_id18.033.18.19. & -0.002 & 0.072 & -0.034 & 0.973\\
\cellcolor{gray!10}{precinct\_id21.126.21.179.} & \cellcolor{gray!10}{0.204} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{2.950} & \cellcolor{gray!10}{0.004}\\
precinct\_id22.061.22.60. & 0.213 & 0.070 & 3.047 & 0.003\\
\addlinespace
\cellcolor{gray!10}{precinct\_id22.124.22.52.} & \cellcolor{gray!10}{0.156} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{2.230} & \cellcolor{gray!10}{0.029}\\
precinct\_id22.137.22.193. & 0.179 & 0.069 & 2.590 & 0.011\\
\cellcolor{gray!10}{precinct\_id22.158.22.203.} & \cellcolor{gray!10}{0.165} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{2.357} & \cellcolor{gray!10}{0.021}\\
precinct\_id22.209.22.172. & 0.188 & 0.070 & 2.699 & 0.009\\
\cellcolor{gray!10}{precinct\_id28.056.28.149.} & \cellcolor{gray!10}{-0.011} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{-0.160} & \cellcolor{gray!10}{0.873}\\
\addlinespace
precinct\_id28.072.28.98. & 0.097 & 0.069 & 1.409 & 0.163\\
\cellcolor{gray!10}{precinct\_id28.139.28.145.} & \cellcolor{gray!10}{0.040} & \cellcolor{gray!10}{0.072} & \cellcolor{gray!10}{0.553} & \cellcolor{gray!10}{0.582}\\
precinct\_id28.163.28.69. & 0.124 & 0.069 & 1.802 & 0.075\\
\cellcolor{gray!10}{precinct\_id29.241.29.172.} & \cellcolor{gray!10}{0.067} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{0.958} & \cellcolor{gray!10}{0.341}\\
precinct\_id34.050.34.39. & 0.342 & 0.069 & 4.947 & 0.000\\
\addlinespace
\cellcolor{gray!10}{precinct\_id34.151.34.125.} & \cellcolor{gray!10}{0.098} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{1.399} & \cellcolor{gray!10}{0.166}\\
precinct\_id36.133.36.92. & 0.358 & 0.069 & 5.179 & 0.000\\
\cellcolor{gray!10}{precinct\_id40.044.40.68.} & \cellcolor{gray!10}{0.236} & \cellcolor{gray!10}{0.072} & \cellcolor{gray!10}{3.275} & \cellcolor{gray!10}{0.002}\\
precinct\_id40.098.40.120. & 0.195 & 0.070 & 2.792 & 0.007\\
\cellcolor{gray!10}{precinct\_id40.134.40.174.} & \cellcolor{gray!10}{0.216} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{3.127} & \cellcolor{gray!10}{0.002}\\
\addlinespace
precinct\_id40.243.40.22. & 0.325 & 0.070 & 4.651 & 0.000\\
\cellcolor{gray!10}{precinct\_id40.244.40.46.} & \cellcolor{gray!10}{0.178} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{2.543} & \cellcolor{gray!10}{0.013}\\
precinct\_id55.228.55.180. & 0.130 & 0.069 & 1.883 & 0.064\\
\cellcolor{gray!10}{precinct\_id58.162.58.98.} & \cellcolor{gray!10}{0.278} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{4.024} & \cellcolor{gray!10}{0.000}\\
precinct\_id58.232.58.231. & 0.203 & 0.069 & 2.940 & 0.004\\
\addlinespace
\cellcolor{gray!10}{precinct\_id67.141.67.123.} & \cellcolor{gray!10}{0.022} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{0.311} & \cellcolor{gray!10}{0.757}\\
precinct\_id69.073.69.35. & 0.070 & 0.069 & 1.015 & 0.313\\
\cellcolor{gray!10}{precinct\_id70.081.70.44.} & \cellcolor{gray!10}{0.062} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{0.899} & \cellcolor{gray!10}{0.372}\\
precinct\_id70.135.70.105. & 0.441 & 0.069 & 6.388 & 0.000\\
\cellcolor{gray!10}{precinct\_id70.221.70.155.} & \cellcolor{gray!10}{0.247} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{3.576} & \cellcolor{gray!10}{0.001}\\
\addlinespace
precinct\_id73.248.73.180. & 0.187 & 0.070 & 2.672 & 0.009\\
\cellcolor{gray!10}{precinct\_id73.251.73.180.} & \cellcolor{gray!10}{0.204} & \cellcolor{gray!10}{0.070} & \cellcolor{gray!10}{2.927} & \cellcolor{gray!10}{0.005}\\
precinct\_id87.017.87.58. & 0.127 & 0.069 & 1.836 & 0.070\\
\cellcolor{gray!10}{precinct\_id87.053.87.68.} & \cellcolor{gray!10}{0.214} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{3.100} & \cellcolor{gray!10}{0.003}\\
precinct\_id87.213.87.24. & 0.033 & 0.070 & 0.469 & 0.641\\
\addlinespace
\cellcolor{gray!10}{precinct\_id98.009.98.12.} & \cellcolor{gray!10}{0.129} & \cellcolor{gray!10}{0.069} & \cellcolor{gray!10}{1.868} & \cellcolor{gray!10}{0.066}\\
year2007 & -0.045 & 0.019 & -2.364 & 0.021\\
\cellcolor{gray!10}{year2011} & \cellcolor{gray!10}{-0.131} & \cellcolor{gray!10}{0.024} & \cellcolor{gray!10}{-5.381} & \cellcolor{gray!10}{0.000}\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: OLS
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summ}\NormalTok{(model1\_ff, }\AttributeTok{model.fit =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{, }\AttributeTok{robust =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{120}\\
Dependent variable & perc\_lib\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{OLS linear regression}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & t val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{0.275} & \cellcolor{gray!10}{0.085} & \cellcolor{gray!10}{3.247} & \cellcolor{gray!10}{0.002}\\
proposed\_turbine & -0.057 & 0.039 & -1.465 & 0.147\\
\cellcolor{gray!10}{precinct\_id10.115s.10.84.} & \cellcolor{gray!10}{0.166} & \cellcolor{gray!10}{0.101} & \cellcolor{gray!10}{1.646} & \cellcolor{gray!10}{0.104}\\
precinct\_id105.038.105.45. & 0.053 & 0.104 & 0.509 & 0.612\\
\cellcolor{gray!10}{precinct\_id14.149.14.79.} & \cellcolor{gray!10}{0.208} & \cellcolor{gray!10}{0.094} & \cellcolor{gray!10}{2.201} & \cellcolor{gray!10}{0.031}\\
\addlinespace
precinct\_id14.168.14.82. & 0.192 & 0.110 & 1.751 & 0.084\\
\cellcolor{gray!10}{precinct\_id18.003.18.1.} & \cellcolor{gray!10}{0.121} & \cellcolor{gray!10}{0.107} & \cellcolor{gray!10}{1.132} & \cellcolor{gray!10}{0.261}\\
precinct\_id18.033.18.19. & -0.002 & 0.101 & -0.024 & 0.981\\
\cellcolor{gray!10}{precinct\_id21.126.21.179.} & \cellcolor{gray!10}{0.204} & \cellcolor{gray!10}{0.157} & \cellcolor{gray!10}{1.299} & \cellcolor{gray!10}{0.198}\\
precinct\_id22.061.22.60. & 0.213 & 0.105 & 2.023 & 0.047\\
\addlinespace
\cellcolor{gray!10}{precinct\_id22.124.22.52.} & \cellcolor{gray!10}{0.156} & \cellcolor{gray!10}{0.103} & \cellcolor{gray!10}{1.509} & \cellcolor{gray!10}{0.135}\\
precinct\_id22.137.22.193. & 0.179 & 0.104 & 1.721 & 0.089\\
\cellcolor{gray!10}{precinct\_id22.158.22.203.} & \cellcolor{gray!10}{0.165} & \cellcolor{gray!10}{0.088} & \cellcolor{gray!10}{1.879} & \cellcolor{gray!10}{0.064}\\
precinct\_id22.209.22.172. & 0.188 & 0.106 & 1.770 & 0.081\\
\cellcolor{gray!10}{precinct\_id28.056.28.149.} & \cellcolor{gray!10}{-0.011} & \cellcolor{gray!10}{0.112} & \cellcolor{gray!10}{-0.099} & \cellcolor{gray!10}{0.921}\\
\addlinespace
precinct\_id28.072.28.98. & 0.097 & 0.104 & 0.934 & 0.353\\
\cellcolor{gray!10}{precinct\_id28.139.28.145.} & \cellcolor{gray!10}{0.040} & \cellcolor{gray!10}{0.111} & \cellcolor{gray!10}{0.359} & \cellcolor{gray!10}{0.721}\\
precinct\_id28.163.28.69. & 0.124 & 0.106 & 1.179 & 0.242\\
\cellcolor{gray!10}{precinct\_id29.241.29.172.} & \cellcolor{gray!10}{0.067} & \cellcolor{gray!10}{0.089} & \cellcolor{gray!10}{0.749} & \cellcolor{gray!10}{0.456}\\
precinct\_id34.050.34.39. & 0.342 & 0.089 & 3.821 & 0.000\\
\addlinespace
\cellcolor{gray!10}{precinct\_id34.151.34.125.} & \cellcolor{gray!10}{0.098} & \cellcolor{gray!10}{0.093} & \cellcolor{gray!10}{1.050} & \cellcolor{gray!10}{0.297}\\
precinct\_id36.133.36.92. & 0.358 & 0.091 & 3.941 & 0.000\\
\cellcolor{gray!10}{precinct\_id40.044.40.68.} & \cellcolor{gray!10}{0.236} & \cellcolor{gray!10}{0.096} & \cellcolor{gray!10}{2.457} & \cellcolor{gray!10}{0.016}\\
precinct\_id40.098.40.120. & 0.195 & 0.092 & 2.123 & 0.037\\
\cellcolor{gray!10}{precinct\_id40.134.40.174.} & \cellcolor{gray!10}{0.216} & \cellcolor{gray!10}{0.090} & \cellcolor{gray!10}{2.399} & \cellcolor{gray!10}{0.019}\\
\addlinespace
precinct\_id40.243.40.22. & 0.325 & 0.098 & 3.314 & 0.001\\
\cellcolor{gray!10}{precinct\_id40.244.40.46.} & \cellcolor{gray!10}{0.178} & \cellcolor{gray!10}{0.095} & \cellcolor{gray!10}{1.873} & \cellcolor{gray!10}{0.065}\\
precinct\_id55.228.55.180. & 0.130 & 0.092 & 1.406 & 0.164\\
\cellcolor{gray!10}{precinct\_id58.162.58.98.} & \cellcolor{gray!10}{0.278} & \cellcolor{gray!10}{0.097} & \cellcolor{gray!10}{2.867} & \cellcolor{gray!10}{0.005}\\
precinct\_id58.232.58.231. & 0.203 & 0.092 & 2.203 & 0.031\\
\addlinespace
\cellcolor{gray!10}{precinct\_id67.141.67.123.} & \cellcolor{gray!10}{0.022} & \cellcolor{gray!10}{0.115} & \cellcolor{gray!10}{0.189} & \cellcolor{gray!10}{0.850}\\
precinct\_id69.073.69.35. & 0.070 & 0.104 & 0.677 & 0.500\\
\cellcolor{gray!10}{precinct\_id70.081.70.44.} & \cellcolor{gray!10}{0.062} & \cellcolor{gray!10}{0.095} & \cellcolor{gray!10}{0.655} & \cellcolor{gray!10}{0.514}\\
precinct\_id70.135.70.105. & 0.441 & 0.128 & 3.451 & 0.001\\
\cellcolor{gray!10}{precinct\_id70.221.70.155.} & \cellcolor{gray!10}{0.247} & \cellcolor{gray!10}{0.111} & \cellcolor{gray!10}{2.217} & \cellcolor{gray!10}{0.030}\\
\addlinespace
precinct\_id73.248.73.180. & 0.187 & 0.108 & 1.720 & 0.089\\
\cellcolor{gray!10}{precinct\_id73.251.73.180.} & \cellcolor{gray!10}{0.204} & \cellcolor{gray!10}{0.102} & \cellcolor{gray!10}{1.995} & \cellcolor{gray!10}{0.050}\\
precinct\_id87.017.87.58. & 0.127 & 0.112 & 1.135 & 0.260\\
\cellcolor{gray!10}{precinct\_id87.053.87.68.} & \cellcolor{gray!10}{0.214} & \cellcolor{gray!10}{0.150} & \cellcolor{gray!10}{1.428} & \cellcolor{gray!10}{0.157}\\
precinct\_id87.213.87.24. & 0.033 & 0.087 & 0.375 & 0.709\\
\addlinespace
\cellcolor{gray!10}{precinct\_id98.009.98.12.} & \cellcolor{gray!10}{0.129} & \cellcolor{gray!10}{0.107} & \cellcolor{gray!10}{1.210} & \cellcolor{gray!10}{0.230}\\
year2007 & -0.045 & 0.024 & -1.876 & 0.064\\
\cellcolor{gray!10}{year2011} & \cellcolor{gray!10}{-0.131} & \cellcolor{gray!10}{0.036} & \cellcolor{gray!10}{-3.686} & \cellcolor{gray!10}{0.000}\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: Robust, type = HC3
\end{tablenotes}
\end{threeparttable}
\end{table}

\textbf{3C.Q1:} Intuition check: Is the \emph{signal-to-noise} ratio for
the treatment estimate greater than \emph{2-to-1}?

\emph{Response:} From the model, signal-to-noise ratio for the treatment
estimate is approximately 1.86. Thus, we cannot say that the
signal-to-noise ratio is greater than \emph{2-to-1}.

\begin{quote}
HINT: Add the argument \texttt{digits\ =\ 3} to the \texttt{summ()}
function above
\end{quote}

\textbf{3C.Q2:} Re-run the \texttt{summ()} function using the
\emph{heteroscedasticity robust standard error adjustment}
(\texttt{robust\ =\ TRUE}). Did the standard error (S.E.) estimates
change? Explain why.

\emph{Response:} Yes, the standard errors increased when using
heteroskedasticity-robust standard errors. This occurred because robust
standard errors relax the assumption of constant error variance and
adjust for potential heteroskedasticity in the residuals.

\textbf{3C.Q3:} Compare results of the model above to the findings from
the fixed effects analysis in the Stokes (2015) study. Why might the
results be similar or different?

\emph{Response:} The estimated effect in this model is similar in
direction and magnitude to Stokes (2015), which also found electoral
backlash from turbine exposure. Differences in statistical significance
likely stem from the smaller sample size (40 samples) and the use of a
simpler model compared to the full study.

\textbf{3C.Q4:} In your own words, explain why it is advantageous from a
causal inference perspective to include year and precinct fixed effects.
Explain how between-level and within-level variance is relevant to the
problem of omitted variable bias (OVB).

\emph{Response (2-4 sentences):} Precinct fixed effects control for
time-invariant characteristics, while year fixed effects capture
province-wide trends that are affecting all precincts. This approach
removes both between-precinct and between-year variation and forces
identification to rely on within-precinct changes over time. By using
only the variation within each level, the fixed effects reduced omitted
variable bias from unobserved factors that not only differed across
precincts or years but that were also constant within them.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{d.-now-using-the-full-sample-estimate-the-treatment-effect-of-wind-turbine-proposals-on-incumbent-vote-share.-use-feols-from-the-fixest-package-to-estimate-the-fixed-effects.}{%
\paragraph{\texorpdfstring{\textbf{3D.} Now using the full sample,
estimate the treatment effect of wind turbine proposals on incumbent
vote share. Use \texttt{feols()} from the \texttt{\{fixest\}} package to
estimate the fixed
effects.}{3D. Now using the full sample, estimate the treatment effect of wind turbine proposals on incumbent vote share. Use feols() from the \{fixest\} package to estimate the fixed effects.}}\label{d.-now-using-the-full-sample-estimate-the-treatment-effect-of-wind-turbine-proposals-on-incumbent-vote-share.-use-feols-from-the-fixest-package-to-estimate-the-fixed-effects.}}

See vignette here:
\href{https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html\#11_Estimation}{fixest
walkthrough}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model2\_ff }\OtherTok{\textless{}{-}} \FunctionTok{feols}\NormalTok{(perc\_lib }\SpecialCharTok{\textasciitilde{}}\NormalTok{ proposed\_turbine }\SpecialCharTok{|}\NormalTok{ precinct\_id }\SpecialCharTok{+}\NormalTok{ year, }
                   \AttributeTok{data =}\NormalTok{ panel\_data,}
                   \AttributeTok{cluster =} \SpecialCharTok{\textasciitilde{}}\NormalTok{precinct\_id)}

\FunctionTok{summary}\NormalTok{(model2\_ff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
OLS estimation, Dep. Var.: perc_lib
Observations: 18,558
Fixed-effects: precinct_id: 6,186,  year: 3
Standard-errors: Clustered (precinct_id) 
                 Estimate Std. Error  t value   Pr(>|t|)    
proposed_turbine -0.04157   0.007682 -5.41144 6.4869e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.070481     Adj. R2: 0.624835
                 Within R2: 0.00224 
\end{verbatim}

\textbf{3D.Q1:} Interpret the model results and translate findings to be
clear to an audience that may not have a background in causal inference
(Econometrics) methods.

In panel data settings, why is clustering by precinct important (i.e.,
\texttt{cluster\ =\ \textasciitilde{}precinct\_id}) ?''

\emph{Response (4-6 sentences):} The model compares each precinct to
itself over time and asks whether Liberal vote share changes after a
wind turbine is proposed, while accounting for province-wide election
trends. The estimate of −0.0416 indicates that, on average, Liberal vote
share in a precinct declines by about 4 percentage points after a
turbine proposal appears relative to that same precinct in other years.
This effect is statistically significant, which suggests that the
decline is unlikely to be due to random chance. In other words,
communities tend to reduce support for the governing party when a wind
turbine is proposed nearby.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{e.-estimate-the-treatment-effect-of-operational-wind-turbines-on-incumbent-vote-share.-use-the-same-approach-as-the-previous-model.}{%
\paragraph{\texorpdfstring{\textbf{3E.} Estimate the treatment effect of
\emph{operational wind turbines} on incumbent vote share. Use the same
approach as the previous
model.}{3E. Estimate the treatment effect of operational wind turbines on incumbent vote share. Use the same approach as the previous model.}}\label{e.-estimate-the-treatment-effect-of-operational-wind-turbines-on-incumbent-vote-share.-use-the-same-approach-as-the-previous-model.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model3\_ff }\OtherTok{\textless{}{-}} \FunctionTok{feols}\NormalTok{(perc\_lib }\SpecialCharTok{\textasciitilde{}}\NormalTok{ operational\_turbine }\SpecialCharTok{|}\NormalTok{ precinct\_id }\SpecialCharTok{+}\NormalTok{ year, }
                   \AttributeTok{data =}\NormalTok{ panel\_data,}
                   \AttributeTok{cluster =} \SpecialCharTok{\textasciitilde{}}\NormalTok{precinct\_id)}

\FunctionTok{summary}\NormalTok{(model3\_ff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
OLS estimation, Dep. Var.: perc_lib
Observations: 18,558
Fixed-effects: precinct_id: 6,186,  year: 3
Standard-errors: Clustered (precinct_id) 
                     Estimate Std. Error  t value   Pr(>|t|)    
operational_turbine -0.092762   0.011739 -7.90195 3.2271e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.070447     Adj. R2: 0.625198
                 Within R2: 0.003206
\end{verbatim}

\textbf{3E.Q1:} Interpret the \texttt{model3\_ff} results as clearly and
\textbf{concisely} as you can.

\emph{Response:} This model compares each precinct to itself over time
and examines whether Liberal vote share changes after a wind turbine
becomes operational, while accounting for province-wide election trends.
The estimate of −0.093 indicates that, on average, Liberal vote share in
a precinct declines by about 9 percentage points once a turbine is
operational relative to that same precinct in other years. This effect
is also statistically significant, which indicates that the decline is
unlikely to be due to random chance. In other words, the electoral
backlash against the governing party is even stronger once turbines are
built and operating.

\textbf{3E.Q2:} Why do you think the effect of proposed wind turbines is
different from operational wind turbines. Develop your own theory about
why incumbent vote share is affected in this way. Use the Stokes (2015)
study to inform your response as needed.

\emph{Response:} The effect of operational wind turbines is larger than
that of proposed turbines because the costs of the policy become more
tangible once turbines are actually built. During the proposal stage,
opposition may be driven uncertainty and anticipation of the project,
but once turbines are operational, residents directly experience the
noise impacts and changes to the local landscape. Stokes (2015) argued
that voters are more likely to punish incumbents when policy costs are
concentrated and can be directly attributed to government decisions. In
addition, operational turbines may reinforce the perception that local
preferences were ignored, which may trigger resentment toward the
governing party. As a result, electoral backlash intensifies when
turbines move from the proposal phase to the implementation phase.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}



\end{document}
